apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo
spec:
  containers:
    - image: asia-southeast1-docker.pkg.dev/k8s-demo-358808/k8s-demo/k8s-demo
      name: k8s-demo
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP